### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by davidgamingzz** [poggit/devirion#11]
`Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 7381522038851265936 bytes) in /home/servers/opfaction/plugins/devirion-master/src/poggit/virion/devirion/RegisterClassLoaderAsyncTask.php on line 36`

Does anyone know what causes this?

**Comment by SOF3** [comment]
This seems to be a pthreads bug. 7381522038851265936 is a number of the magnitude of 2^62...

**Comment by SOF3** [comment]
cc @dktapps

**Comment by dktapps** [comment]
It's the same old bug we've been seeing for years. Until we have a way to reproduce it, it's not helpful.
